
modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="skyislanddimension"
version="${file.jarVersion}"
displayName="Sky Island Dimension"
authors="TheNyfaria"
description='''
'''
